### PR TITLE
Conway's game of life for you

### PR DESCRIPTION
**Pull request by slobberchops**
Hi, just letting you know that I've been using your ROP software for all sorts of things that it wasn't designed for, however, there is one thing I made that you might like to have in the 'art' directory.  See life.py in my repository.  It's an implementation of Conway's Game of Life: https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life

Lots of room for improvements, but something useful.

In case your interested, the other horrible stuff I've been doing is creating composite arts so that one art is composed of many other.  Using it for doing rotation (similar to what your art.py does by default), changing selected arts, global effects (like fadeout) or mixing arts together.

### CODE REVIEW

**Comment by ak15199** [comment]
Hey Rafe, 

I'm thrilled, and props to you - there's a lot of good stuff in here. Thank you!

Work on rop has slowed since I moved to Chicago to run Devops for gogo, but I'll be getting back to it soon. 

When I do, I'll want to tease apart a few things and figure out how to best merge (like id rather not include idea files in the repo, but stuff like del support, git ignore, and those new arts are a godsend. 

I saw that you had a timeit in mirror.py. Did you see the profiling code that's included already?

Alex

**Comment by ak15199** [comment]
OK, I just pushed a slightly modified life (+your gitignore and driver additions) to the integration branch. There's more that I'll want to get to, but these seemed the simplest.

**Comment by slobberchops** [comment]
Great, very pleased you could find something to use.

**Comment by slobberchops** [comment]
Just so you know, now that I left Google/Alphabet, I'm actually learning how to properly use GitHub so that I don't send you such a mess in the future.

Burning man went well, I should say.  Here's a link with the project lead demonstrating the LED mirror we partially used ROP to run: https://goo.gl/photos/AbosL64XNViEUmmEA

Being temporarily and willingly unemployed I have some time to maybe work on adding things to this project if you are interested.

In the mean time, I can close this pull request out so it doesn't bother you anymore.

**Comment by ak15199** [comment]
That, my friend, is a super sweet piece of work. 

When I saw how much stuff was in that merge request, I was a bit WTF. But it's one of those things you just have to figure out, right? :)

I hadn't totally finished pulling stuff out of the merge request, but the last couple of months have been stupid busy with creating a DevOps team at Gogo and getting started on moving all of our apps to AWS. 

Having said that, I'd be delighted to collaborate with you on this stuff. 

Alex

**Pull request closed without merging**
